const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{speedY: 0},
	{driftX: 0},
	{planet: 0},
	{ballRight: 0},
	{ballLeft: 0},
	{Rotate: 0},
	{controller: 0},
	{touchLeft: 0},
	{touchRight: 0},
	{lineScore: 0},
	{Keyboard: 0},
	{Touch: 0},
	{bg: 0},
	{textScore: 0},
	{Tween: 0},
	{pauseFrame: 0},
	{btnPaused: 0},
	{btnSfx: 0},
	{btnMusic: 0},
	{settings: 0},
	{Audio: 0},
	{pauseBlank: 0},
	{LocalStorage: 0},
	{textHighScore: 0},
	{varScore: 0},
	{isSfxOn: 0},
	{isMusicOn: 0},
	{VarHighScore: 0}
];

self.InstanceType = {
	planet: class extends self.ISpriteInstance {},
	ballRight: class extends self.ISpriteInstance {},
	ballLeft: class extends self.ISpriteInstance {},
	controller: class extends self.ISpriteInstance {},
	touchLeft: class extends self.ISpriteInstance {},
	touchRight: class extends self.ISpriteInstance {},
	lineScore: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	bg: class extends self.ISpriteInstance {},
	textScore: class extends self.ITextInstance {},
	pauseFrame: class extends self.ISpriteInstance {},
	btnPaused: class extends self.ISpriteInstance {},
	btnSfx: class extends self.ISpriteInstance {},
	btnMusic: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	pauseBlank: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	textHighScore: class extends self.ITextInstance {}
}